export const projectDatadisplay = [
  {
    name: 'Quick Learn',
    des: 'A full-stack employee learning platform enabling companies to track daily skill growth. Features automated cron jobs that deliver personalised lesson emails at 9 AM and 5 PM, and a streak-based leaderboard system driven by read-time metrics to boost engagement.',
    techStack: ['Next.js', 'NestJS', 'PostgreSQL', 'AWS', 'DigitalOcean', 'Tailwind'],
    githubLink: null,
    deployLink: null,
    imgUrl: null,
    featured: true,
    highlights: [
      'Automated lesson email delivery via cron jobs at 9 AM and 5 PM',
      'Streak-based leaderboard using read-time metrics to drive engagement',
    ],
  },
  {
    name: 'SocialBinge',
    des: 'A full-stack social media platform with authentication, CRUD-based post management, follow system, and tagging. Built with TypeScript on both client and server. Data persisted on MongoDB with clean REST API design and reusable React components.',
    techStack: ['React', 'Node.js', 'TypeScript', 'MongoDB'],
    githubLink: 'https://github.com/GaganDamoriya/SocialBinge',
    deployLink: 'https://socialbingee.netlify.app/',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/egcharitywebsite.appspot.com/o/files%2Fsm3.png?alt=media&token=ba150b0d-8a88-4fb9-b918-2144abe3ffae',
    featured: true,
    highlights: [],
  },
  {
    name: 'TradeCoin',
    des: 'A cryptocurrency price tracker with real-time data from the CoinRanking API. Clean, responsive UI displays current prices, market cap, and 24h change for top coins.',
    techStack: ['React', 'Node.js'],
    githubLink: 'https://github.com/GaganDamoriya/CryptoMark',
    deployLink: 'https://showcoinranking.netlify.app/',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/egcharitywebsite.appspot.com/o/files%2Ftradecoin_website.jpg?alt=media&token=04a0d64d-6d70-44cc-84ef-1b180320d738',
    featured: false,
    highlights: [],
  },
  {
    name: 'picUrShow',
    des: 'A movie recommendation site with genre-based sorting powered by the TMDB API. Modern design built with React and SCSS — "when bored and unsure what to watch, let picUrShow decide."',
    techStack: ['React', 'Node.js', 'SCSS'],
    githubLink: 'https://github.com/GaganDamoriya/pickUrshow',
    deployLink: 'https://thepicurshowebsite.netlify.app/',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/egcharitywebsite.appspot.com/o/files%2Fmovieweb11.jpg?alt=media&token=2492a4a8-87af-4c70-944b-643360b2822e',
    featured: false,
    highlights: [],
  },
  {
    name: 'LetsHelp',
    des: 'A charity platform that aggregates foundations needing immediate fundraising attention, with a direct donation checkout powered by Stripe API (test mode).',
    techStack: ['React', 'Node.js', 'Firebase', 'Stripe'],
    githubLink: 'https://github.com/GaganDamoriya/EGcharityWebsite',
    deployLink: 'https://letshelpcharity.netlify.app/',
    imgUrl: 'https://firebasestorage.googleapis.com/v0/b/egcharitywebsite.appspot.com/o/files%2Fweb3.jpg?alt=media&token=f415013f-0944-4539-b021-58a247400959',
    featured: false,
    highlights: [],
  },
];
